name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure the same Python version is used

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils  # Required for Python 3.12

    - name: Set up virtual environment and install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install numpy --upgrade --force-reinstall  # Ensure compatible version of numpy
        pip install pmdarima --upgrade --force-reinstall  # Rebuild pmdarima
        pip install -r requirements.txt
        pip install pytest pytest-cov  # Include pytest plugins for coverage

    - name: Debug environment
      run: |
        source .venv/bin/activate
        python --version
        pip list  # Debugging installed dependencies

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest --cov=. --cov-report=xml  # Generate coverage report

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml